apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: raft-lab
type: Opaque
stringData:
  # Change these before using this outside a throwaway local kind cluster.
  SUPERUSER_USERNAME: postgres
  SUPERUSER_PASSWORD: postgres
  REPLICATION_USERNAME: replicator
  REPLICATION_PASSWORD: replicator
